### PR TITLE
replace global with globalThis

### LINKED ISSUE #581: global is not defined
Hello everyone!

There's an issue with sockjs that already existed for years.

```
Error: Uncaught (in promise): ReferenceError: global is not defined
ReferenceError: global is not defined
```

It was opened before https://github.com/sockjs/sockjs-client/issues/439 but wasn't fixed.
I know the hotfix to add `(window as any).global = window;` into polyfills. 

But is it going to be fixed?

### PR DESCRIPTION
**Pull request by lil5**
Fixes #581

**Problem**

> On the web you can use [window](https://developer.mozilla.org/en-US/docs/Web/API/Window/window), [self](https://developer.mozilla.org/en-US/docs/Web/API/Window/self), or [frames](https://developer.mozilla.org/en-US/docs/Web/API/Window/frames) - but in [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Worker) only self will work. In Node.js none of these work, and you must instead use global. The this keyword could be used inside functions running in non–strict mode, but this will be undefined in modules and inside functions running in strict mode.

**Fix**

The `globalThis` property provides a standard way of accessing the global this value (and hence the global object itself) across environments. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
hey! thanks for the change! can you please add tests to verify the changes?

**Comment by JulesLecuir** [comment]
Thanks @lil5 ! Looking forward to having this PR merged :)

**Comment by lil5** [comment]
@auvipy I'm not sure how to do that more than I've already done.

Have you looked at the list of files I changed?

Tests that previously used `global` now use `globalThis` and it works just fine.

**Comment by lil5** [comment]
@auvipy Would you like me to run `npm run glup release` and commit the `/dist/` files before you merge?

**Pull request closed without merging**
