### PR TITLE
#403 Provide SockJS config for minimum transport fallback timeout

### PR DESCRIPTION
**Pull request by antonselukh**
One of our clients experiences a poor network QoS and falling back to xhr makes it even worse. A simple minimum timeout could solve the issue #403

### CODE REVIEW

**Comment by acierto** [comment]
Have the same problem with a short timeout.
Any williness to accept this PR and release a new version?

**Comment by antonselukh** [comment]
After using this fix, the customers behind The Great Firewall have no more complains

**Comment by aalbul** [comment]
+1. Please merge 👍

**Comment by aniketd** [comment]
This is very much needed. 👍

**Comment by JeanCarriere** [comment]
+1 👍

**Comment by shengbeiniao** [comment]
mark

**Comment by sorteam** [comment]
Have the same problem. Please, add this functionality.

**Comment by TalSheffer** [comment]
This is a small fix for a major issue.
Without that fix we can't use sockjs-client.
Pls marge this PR or one of the other PRs that fix #403

**Comment by brycekahle** [comment]
Fixed in https://github.com/sockjs/sockjs-client/commit/537352c7d8db0b6fbd3b4d63be4a98cb9af6062a

**Pull request closed without merging**
