### PR TITLE
Pass localAddress property from SockJS options to transports

### PR DESCRIPTION
**Pull request by prawnsalad**
re. https://github.com/sockjs/sockjs-client/issues/272
Dependant on this patch being merged into faye-websocket-node: https://github.com/faye/faye-websocket-node/pull/49

### CODE REVIEW

**Comment by prawnsalad** [comment]
Not sure why Travis is failing.. all tests pass on my local machine?

**Comment by brycekahle** [comment]
@prawnsalad It is tricky and finicky to do this testing in a virtualized selenium environment so there are spurious failures.

**Comment by brycekahle** [comment]
Also, have you tested this in a browser? I wonder what the native `Websocket` object will do with those extra arguments.

**Comment by brycekahle** [comment]
It looks like this PR is invalid now because the upstream change was not merged.

**Pull request closed without merging**
