### PR TITLE
wrapped transport exception to error event to prevent from unhandled …

### PR DESCRIPTION
**Pull request by vadzappa**
…exception thrown when connecting after async info loaded

### CODE REVIEW

**Comment by brycekahle** [comment]
What specific exception was being thrown?

**Comment by vadzappa** [comment]
Unfortunately exception had only ":" in it without any meaningful data and is coming only from FireFox web browser.

**Comment by brycekahle** [comment]
If you can reproduce with debug logs on, that would help narrow down the problem. I'm a little uncomfortable adding a try/catch without knowing what exception is being thrown.

**Comment by brycekahle** [comment]
Closing due to inactivity.

**Pull request closed without merging**
