### PR TITLE
Migrate to ts

### PR DESCRIPTION
**Pull request by luisvt**

### CODE REVIEW

**Comment by brycekahle** [comment]
Whoa. Thanks for the pile of work. Pardon my TypeScript ignorance, but I have a few questions.

1. Is there a way to incorporate TypeScript without sacrificing the ability to use the client in Node.js? I'd prefer to avoid a build step for Node.js, but I'm guessing that may not be possible.

2. I'm not seeing any type annotations? Isn't that a main benefit of using TypeScript? I'd be curious if any bugs are uncovered once this is done.

3. It appears some of the files are not being recognized as renames. I'd like to maintain git history if possible. I know you can do `git mv` when in process, but there may be a way to fix this after the fact. If you get stuck figuring this out, let me know and I can help investigate.

**Comment by luisvt** [comment]
1. When you run `tsc` in the project folder, it will generate a JS and a JS.map file. Later you can do `gulp test` or whatever gulp task that will run over the generated files.

2. Right now to maintain most of the original code I didn't add too much types. There were some methods that were slightly changed to be able to use Typescript.

**Comment by luisvt** [comment]
Could you check why tests fail?

**Comment by brycekahle** [comment]
@luisvt The tests at the moment always fail.

I'll be honest, I don't see much benefit of migrating to TypeScript unless it has type annotations. I also cannot review this PR as is, for the following reasons:

1. The file renames were not done in a git friendly way, so it sees them as a full delete and create. I cannot tell what changed.
2. The changes made to comply with TypeScript were done in the same commit, so I cannot tell what changes were made for TypeScript and what effects those changes may have.

If this PR could be structured with the following series of commits, I could at least have more information:

1. rename files with git mv (no changes to files)
2. ES6 syntax changes
3. TypeScript changes

I understand I'm asking you to basically redo your work. In the future I would advise raising the issue on a project before undertaking a lot of work.

**Comment by brycekahle** [comment]
@luisvt I'm going to close this PR since it seems abandoned. If you decide to pickup this work following my suggestions, please open up a new PR. Thanks!

**Pull request closed without merging**
