### PR TITLE
Added esbuild

### PR DESCRIPTION
**Pull request by Neizan93**
Added ESBuild to fix optimization bailouts on TypeScript frameworks like Angular.

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
can you please share more context about the change requested?

**Comment by auvipy** [comment]
thanks. I will merge it soon. just need to fix the CI from my side

**Comment by Neizan93** [comment]
> thanks. I will merge it soon. just need to fix the CI from my side

thank you =)

**Review by auvipy — CHANGES_REQUESTED** [review]
can you please add some tests to verify the proposed changes?

**Comment by lagoshny** [comment]
@Neizan93 , @auvipy Any news?

**Review by auvipy — APPROVED** [review]

**Comment by lagoshny** [comment]
Great, thank you! 
@auvipy Can you publish this changes in new lib version?

**Comment by auvipy** [comment]
we got an issue reported here https://github.com/sockjs/sockjs-client/issues/664, can you please fix this? @https://github.com/sockjs/sockjs-client/issues/664

**Comment by Neizan93** [comment]
> we got an issue reported here #664, can you please fix this? @Neizan93

just delete package lock and install packages to fix it

**Pull request merged**
