### PR TITLE
URI malformed fix, for the event source error when message contains %

### PR DESCRIPTION
**Pull request by yadue**
For eventsource when message contains % followed by space it throws URI malformed message. That pull request fixes that by escaping % not followed by any char.

### CODE REVIEW

**Comment by brycekahle** [comment]
@yadue `%` in the source message should be encoded as `%25`, and thus would be decoded properly. How did you get a message on the wire that wasn't encoded properly?

**Comment by yadue** [comment]
I’m not sure what are you asking about, sockjs latest plus stomp and spring boot. Object { title: ‘ % ‘ } stored as it is in db and returned from spring boot as it is. It works for all transports correctly excluding eventsource so my assumption is that event source works incorrectly. For websocket xhr message looks the same.

**Comment by yadue** [comment]
@brycekahle actually I think decodeURI might be not even required, none of the others receivers is using that. I'm not sure at this point why it has been added but it's causing issues for us if the message body contains % followed by space.

**Comment by brycekahle** [comment]
There is some selective escaping happening on the server-side.

https://github.com/sockjs/sockjs-node/blob/14a5c3cf097126bde74436d001816c53a0593d43/src/trans-eventsource.coffee#L17

So this should probably be fixed to selectively decode as well.

**Comment by yadue** [comment]
@brycekahle I’m leaving my proposition as it is currently, we had to urgently make a fork as our customers started to having issues with receiving data. Hopefully it will get merged or something else will be introduced to avoid issues with % character.

**Comment by brycekahle** [comment]
I'm fixing this on the server side. See https://github.com/sockjs/sockjs-node/commit/b417cd704b863be3d64f78b2bc7bcf747034f7a3

**Comment by brycekahle** [comment]
On further investigation, I'm having trouble reproducing your issue. I'm seeing proper escaping from the server side, even without the change I linked. Are you sure there isn't something in stomp/spring that is decoding a second time?

**Comment by yadue** [comment]
@brycekahle We are using sockjs at it is no extra decoding/encoding. The case was difficult to reproduce and we had that issue appearing all the time. Since I created fork of this repo and fixed that transport the way the others were done all the issues are gone. It's been almost a year now and I don't remember how to reproduce that.

**Comment by yadue** [comment]
Hey @brycekahle. Yesterday I had another issue with eventsource and had to dig out to find original issue and got it. Here's the raw response coming from spring boot:
https://pastebin.com/mEUdUTVH

The same raw response comes from other transport methods, but fails only with event source because decodeURI function not able to parse that message. At the end of day I ended up with function like this:
```
function decodeURISafe(s) {
  return decodeURI(s.replace(/%(?![0-9][0-9a-fA-F]+)/g, '%25'));
}
```

in that example decodeURI fails parsing exactly that field:
`\"lastName\":\"#@%!~`%^&*() źńśćół\",`

My function escapes those signs.

**Pull request closed without merging**
