### PR TITLE
Bump debug to latest

### PR DESCRIPTION
**Pull request by lopopolo**
If this patch is merged and accepted, could the maintainers push a new release to npm?

### CODE REVIEW

**Comment by brycekahle** [comment]
Do you need the latest `debug` for a particular reason?

**Comment by lopopolo** [comment]
I want to remove duplicate deps with semver incompatible versions from my lock file.

**Comment by brycekahle** [comment]
I don't remember the exact error at the moment, but I'm pretty sure I avoided upgrading `debug` because it was causing problems during testing.

**Comment by brycekahle** [comment]
I remembered why. It is because debug@4 starts using `let/const`, which limits which browsers can use this library.

**Pull request closed without merging**
