### PR TITLE
Add bower.json

### PR DESCRIPTION
**Pull request by artemkaint**

### CODE REVIEW

**Comment by carchrae** [comment]
fixed, but only in the git repo version.  bower main is broken (points to ./lib/entry.js) if you install the latest version (1.0.0).

you can workaround by specifying the github commit instead of the version.  

```
    "sockjs-client": "git@github.com:sockjs/sockjs-client.git#f529e8855e4649df81af8de1abe251612c59c69c"
```

**Comment by brycekahle** [comment]
What do you mean by 'git repo version'? Bower only works from git repos.

**Comment by carchrae** [comment]
i meant referring to the specific git commit instead of the version number.  but yes it is fine now.  perhaps i had a cached version, so i could have just done `bower cache clean sockjs-client`.  

i'm actually a bit confused because i can't even find the broken version on github.  it had `main : 'lib/entry.js'` or something like that.

**Comment by brycekahle** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
