### PR TITLE
Sockjs 1.03 not running on IE8/IE7 browsers since apply method missing

### LINKED ISSUE #276: BUGFIX IE 11 Emulated to 8
IE 11 Emulation mode for 8 have a Problem (global.console[level].apply).
Add try catch block:
```
['log', 'debug', 'warn'].forEach(function (level) {
	try {
		var levelExists = global.console && global.console[level] && global.console[level].apply;
		logObject[level] = levelExists ? function () {
			return global.console[level].apply(global.console, arguments);
		} : (level === 'log' ? function () {} : logObject.log);
	} catch (e) {};
});
```
and is's works! ;-)

### PR DESCRIPTION
**Pull request by syberkitten**
added fix for old browsers such as IE7/8 were console.log
does not have an apply function.
using try catch we are take care that everything works.
tested on IE8/IE7 via Edge (IE11).

Fixes #276

### CODE REVIEW

**Comment by syberkitten** [comment]
I'm still having issues with IE8 in certain cases, but this was an error that prevented anything from running.

**Comment by brycekahle** [comment]
Interesting that IE8 throws an error. This exact code is meant to detect if `apply` exists or not.

**Comment by brycekahle** [comment]
What was the error that was thrown? Can you also fix the indentation?

**Comment by syberkitten** [comment]
The error that I was getting is: "Object doesn't support this action"
to reproduce, open IE11, open console, change to Edge emulation to IE 8.
write in console log:
console.log.apply

In IE8 and earlier, if a property does not exist an exception is thrown
rather the yielding back 'undefined'

**Comment by brycekahle** [comment]
Ok. It looks like you changed to either 4 space indentation or tabs. It should be 2 space indentation. Sorry to be so picky.

**Comment by syberkitten** [comment]
lol, first commit should be very picky!..)

**Comment by syberkitten** [comment]
lol, got it :)

**Pull request merged**
