### PR TITLE
Upgraded url-parse to ^1.0.0.

### LINKED ISSUE #218: Firefox: too much recursion (1.0.0-beta.6)
On Firefox I get "too much recursion" pointing to this line:

https://github.com/sockjs/sockjs-client/blob/b912ce19a2b0069575848ddfd740a3e0980fc652/dist/sockjs-1.0.0-beta.6.js#L5076

This file is in the /dist folder, I don't know where it is located in the actual source.

In Chrome it is working fine, just happens on Firefox.

### PR DESCRIPTION
**Pull request by elierotenberg**
Fixes #218 in FF 35.0.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
Do these tests always fail or is the fault of my lib? I can't find any decent output in the travis-ci logs here =/

**Comment by elierotenberg** [comment]
I'm afraid they always fail.
https://travis-ci.org/sockjs/sockjs-client/builds

**Comment by lpinca** [comment]
:+1:

**Comment by lpinca** [comment]
@brycekahle can we get a release with this fix? 1.0.0-beta.11?

**Comment by brycekahle** [comment]
@lpinca released 1.0.0-beta.11

**Comment by brycekahle** [comment]
@lpinca 11 had a build mistake. Use 1.0.0-beta.12 instead

**Comment by lpinca** [comment]
Thank you.

**Pull request merged**
